package aof

import (
	"fmt"
	"os"
	"path/filepath"
)

func GenerateAgent(specPath, outDir, baseKernel string) (AgentInstance, error) {
	result, err := CompileFile(specPath)
	if err != nil {
		return AgentInstance{}, err
	}
	crystals, err := Forge(result.Morphogen.Identity.Domain, result.Crystals)
	if err != nil {
		return AgentInstance{}, err
	}
	agent := Differentiate(baseKernel, specPath, result.Morphogen, crystals)
	if err := writeAgent(outDir, agent, result); err != nil {
		return AgentInstance{}, err
	}
	return agent, nil
}

func writeAgent(outDir string, agent AgentInstance, result CompileResult) error {
	if err := os.MkdirAll(filepath.Join(outDir, "crystals"), 0o755); err != nil {
		return err
	}
	if err := WriteJSON(filepath.Join(outDir, "agent.json"), agent); err != nil {
		return err
	}
	if err := WriteJSON(filepath.Join(outDir, "compiled.json"), result); err != nil {
		return err
	}
	for _, c := range agent.Crystals {
		if err := WriteJSON(filepath.Join(outDir, "crystals", c.ID+".json"), c); err != nil {
			return err
		}
	}
	if err := os.WriteFile(filepath.Join(outDir, "system.md"), []byte(BuildSystemPrompt(agent)), 0o644); err != nil {
		return err
	}
	readme := fmt.Sprintf("# %s Agent\n\n%s\n\nGenerated by metagent. Use `system.md` as the agent contract and `agent.json` as runtime metadata.\n", agent.Domain, agent.Description)
	return os.WriteFile(filepath.Join(outDir, "README.md"), []byte(readme), 0o644)
}
